// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Data;

namespace NewsPortal.Migrations
{
    [DbContext(typeof(NewsPortalContext))]
    [Migration("20210807083430_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("NewsPortal.Model.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AName")
                        .HasColumnType("TEXT");

                    b.Property<string>("APassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("AUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorID");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("NewsPortal.Model.Categories", b =>
                {
                    b.Property<int>("CategoriesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NewsPortal.Model.News", b =>
                {
                    b.Property<int>("NewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HLine")
                        .HasColumnType("TEXT");

                    b.Property<int>("NAuthor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("NDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NDetails")
                        .HasColumnType("TEXT");

                    b.HasKey("NewsID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("NewsPortal.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
